### ISSUE TITLE
Review cfp page text

### ISSUE THREAD

**Issue by vvojvoda** [WebCampZg/conference-web#10]
Conference takes place on Saturday, 4th October 2014 in Zagreb.
All talks are 25 minutes, including 5 minutes for Q&A.
Prior experience is not a prerequisite, we welcome first timers.
Talks may be in English or Croatian, but we’d be extra happy if you choose to speak in English.
Multiple talk submissions are welcome.
First 30 submissions get free tickets.
For more details see the conference web site http://2015.webcampzg.org.

**Comment by vvojvoda** [comment]
@ihabunek @retro @niksy

**Comment by ihabunek** [comment]
Nisu sva predavanja 25 min.
Predavanja moraju biti na engleskom.
Makni ovo sa prvih 30 i besplatnom kartom.

Dodati:

Our speaker package includes:
- Full conference pass
- 2 complimentary hotel nights for speakers remote to the area
- Lunch and other activities included in the regular conference
- Speakers dinner on October 2nd
- A goodie bag with a speaker's T-shirt and other swag

**Comment by denibertovic** [comment]
Datum je _opet_ krivi. Saturay 3rd.

**Comment by denibertovic** [comment]
This is fixed in current master. The text is editable from the admin interface. For now I've added a fixture for this year. Closing.
