### ISSUE TITLE
Add slot for media partner

### ISSUE THREAD

**Issue by vvojvoda** [WebCampZg/conference-web#101]
Text: "Glavni medijski partner"
Place between standard and supporter

**Comment by niksy** [comment]
- Main media sponsor should be larger than other media sponsors
- Main media sponsor should have text below which explains that they are "The Big Kahuna"
- Media sponsors should be parallel (i.e. on same line)

**Comment by ihabunek** [comment]
- main media sponsor - size similar to standard sponsor
- other media sponsors - size similar to supporter

**Comment by niksy** [comment]
Done.
