### ISSUE TITLE
Sponsor logos gone mad

### ISSUE THREAD

**Issue by msvrtan** [WebCampZg/conference-web#103]
seems that issue is on ~1400px or more screen, on smaller ones seems ok
- [ ] locastic logo is weirdly squeezed down
- [ ] revolucija logo is weirdly squeezed down
- [ ] buckhill logo is weirdly squeezed down

Chrome Version 45.0.2454.85 (64-bit) MacOSX

![screen shot 2015-09-19 at 15 38 50 3](https://cloud.githubusercontent.com/assets/1780572/9976441/a397cdb8-5ee4-11e5-9814-fa093fcfb86a.png)

Firefox 40.0.3 MacOSX
<img width="1440" alt="screen shot 2015-09-19 at 15 38 50 2" src="https://cloud.githubusercontent.com/assets/1780572/9976439/9781e84c-5ee4-11e5-8d61-6ad5d54c43bf.png">

Safari Version 8.0.7 (10600.7.12) MacOSX

![screen shot 2015-09-19 at 15 38 50](https://cloud.githubusercontent.com/assets/1780572/9976442/aa51b9fc-5ee4-11e5-9f1d-043b3dd36127.png)

**Comment by niksy** [comment]
Fixed.
