### ISSUE TITLE
Not possible to add paper application

### ISSUE THREAD

**Issue by ihabunek** [WebCampZg/conference-web#105]
https://2015.webcampzg.org/admin/cfp/paperapplication/add/

The form has no way to pick cfp and applicant. 

Implementation should be similar to picking the user in:
https://2015.webcampzg.org/admin/cfp/applicant/add/

**Comment by denibertovic** [comment]
Fixed here: 52a33b5e85b7ba4da9d5ad08b89fcd19ad86ad44
