### ISSUE TITLE
Inproper name attribute value for talk duration?

### ISSUE THREAD

**Issue by niksy** [WebCampZg/conference-web#11]
I suppose it should be something like `talk_duration` instead of `skill_level`?

https://github.com/WebCampZg/conference-web/blob/master/cfp/templates/cfp/cfp_form.html#L110-L123

**Comment by denibertovic** [comment]
Yeah this would get fixed when we start using django forms and the partial from partials/form.html and form-field.html. We will not need to hand code this.

**Comment by denibertovic** [comment]
Let me know when the styling support this and I'll make the switch,

**Comment by niksy** [comment]
Changes regarding form fields (classes added to wrapper, not the input element itself) are already present in master branch, so code away :)

**Comment by denibertovic** [comment]
Thanks!

**Comment by denibertovic** [comment]
Fixed in master.
