### ISSUE TITLE
Missing supporter logo

### ISSUE THREAD

**Issue by msvrtan** [WebCampZg/conference-web#136]
We forgot to add https://www.procurios.com as a supporter

![procurios rgb](https://user-images.githubusercontent.com/1780572/46016633-98449a80-c0d5-11e8-8bc3-8b24ce36bbb3.png)

**Comment by senko** [comment]
There, I fixed it: https://2018.webcampzg.org/sponsors/procurios/

**Comment by msvrtan** [comment]
Dank je!
