### ISSUE TITLE
Add Cookie banner

### ISSUE THREAD

**Issue by denibertovic** [WebCampZg/conference-web#28]
:(

**Comment by niksy** [comment]
@denibertovic changes available on `cookie-policy` branch. Is it possible to display that chunk of HTML only if cookie is not present (some if-else in from template engine)? I can do it with JS, but I would like to avoid outputting markup which is not necessary in majority of cases. On the other hand, I can generate that markup with JS…

**Comment by denibertovic** [comment]
@niksy i was just going to use this: https://github.com/dobarkod/cookie-banner

**Comment by niksy** [comment]
@denibertovic you could’ve said so :D I’ve got the whole functionality already implemented on branch I’ve mentioned; as for the markup, I think I will go with JS generate, will do it later this day. Is that OK with you?

What we need is:
- Some default text which explains what this is
- Page with additional description?

**Comment by denibertovic** [comment]
I assigned the issue to myself though. :D The solution above already has markup and hosting and everything solved for us. Well possibly not hosting, since we're on https....

**Comment by denibertovic** [comment]
I would rather use the proven solution instead of re-implementing our own... Unless you also used some library, I haven't had the time to look at the branch yet, sorry.

**Comment by niksy** [comment]
No, just a simple cookie setter/getter when you click on button with which you will agree to default cookie policy. It really isn’t something big, and the whole banner thing shouldn’t be too complicated :) + we should also style it to our brand which is already done (RWD style).

**Comment by niksy** [comment]
Done! Available on branch `cookie-policy`.
