### ISSUE TITLE
Replace fixtures with data migrations

### ISSUE THREAD

**Issue by denibertovic** [WebCampZg/conference-web#29]
Django 1.7 doesn't load fixtures by default. The recommended way is to use data migrations.

**Comment by vvojvoda** [comment]
CFP fixtures are loaded inside the migrations. What else needs to be added? Plus, all of the fixtures are currently loaded right? Can this be moved to some future milestone?

**Comment by denibertovic** [comment]
@vvojvoda The fixtures where not loaded on production when running manage.py migrate. I loaded them manually with manage.py loaddata. The official docs for 1.7 say that the new migrations do not automatically load fixtures the way south did, and that we should use data migrations for this.

**Comment by vvojvoda** [comment]
@denibertovic I was referring to this when I said that CFP fixtures are loaded inside the migrations: https://github.com/WebCampZg/conference-web/blob/master/cfp/migrations/0002_auto_20150301_1827.py

**Comment by denibertovic** [comment]
@vvojvoda i missed that. thanks.
