### ISSUE TITLE
Improve CFP submit process

### ISSUE THREAD

**Issue by niksy** [WebCampZg/conference-web#33]
- Add message on CFP to inform users they should login before submitting proposal
- Move signup link to top and make it more visible

**Comment by niksy** [comment]
@denibertovic @vvojvoda login form is generic for all parts of site that require authentication. Can this be more configurable so we can customize it with more descriptive messages and next actions?

**Comment by vvojvoda** [comment]
@niksy: we can use the django.contrib.messages framework for that.

**Comment by denibertovic** [comment]
@niksy yeah we should use the messages framework for that...we already use it for the global notifications. Where do we need to insert what message?

**Comment by niksy** [comment]
@denibertovic at the top of the login form.

**Comment by denibertovic** [comment]
@niksy Umm the position and styling is defined in ui/base.html.

**Comment by niksy** [comment]
@denibertovic I know, I’m looking for something specific to CFP - if the "referral" link is CFP related, we should display some CFP related message. If that’s too much, maybe we can display some generic message in all cases (e.g. "To view this part of page, you must be logged in." or something like that)
