### ISSUE TITLE
Add call for proposals text to web

### ISSUE THREAD

**Issue by msvrtan** [WebCampZg/conference-web#34]
There is no call for proposals text on web explaining all of the stuff that was sent via newsletter (like we had it always before -> https://2014.webcampzg.org/cfp/ )

**Comment by vvojvoda** [comment]
@niksy /cfp now leads to interim announcement page, form is at /cfp/new/ 
it needs to be styled to resemble the newsletter.
You can checkout branch 'issue_34'
