### ISSUE TITLE
finding the "submit proposal" link

### ISSUE THREAD

**Issue by grobmeier** [WebCampZg/conference-web#43]
I have submitted more than one talk.  Once I added my talk, I was sent to the "Edit my data" page, where I also could edit submissions. However, I had difficulties to easily submit another one. First I hit the "Submit" button on the bottom, which would just submit changes to my profile. Then I found out I would need to go to the top right, hit "Call for Proposals" and click another time. Maybe an "Add another proposal" link beyond the list of talks would be helpful.

**Comment by denibertovic** [comment]
Fixed here: 74bd8043001767f584c86e22118b758f9402bafe 

Closing.
