### ISSUE TITLE
Add user group logos

### ISSUE THREAD

**Issue by ihabunek** [WebCampZg/conference-web#49]
Add user group logos beneath the sponsor logos. 

Similar to last year's web https://2014.webcampzg.org/.

**Comment by niksy** [comment]
These are from last year: https://github.com/WebCampZg/2014.static/tree/master/_site/content/images/organizers

No SVGs, though :/ @ihabunek where can we get those? Ask around or you have them somwhere?

**Comment by ihabunek** [comment]
Look what I found: 
https://drive.google.com/drive/u/0/folders/0B4QM7L_ivXyrdk42aGFpN2VQOTg/0B4QM7L_ivXyrUzgwYmRDN0xsNTA/0B0vOgSsarh2WRnppeUE2RGU4b3c/0B0vOgSsarh2WMUdjZ08yQm1zbnM

It will require converting to SVG. Please upload SVGs to the drive so we have them.

Yell if anything is missing.

**Comment by niksy** [comment]
@denibertovic do we need admin interface for this like the one for sponsors, or should we do this manually? Maybe keep it consistent with sponsors and have admin interface?

**Comment by niksy** [comment]
We don’t have logos for these user groups:
- Lambda Zagreb
- Python Hrvatska (we have generic Python logo)
- Web Designers Hrvatska
- Zagreb Software Testing Club

**Comment by denibertovic** [comment]
Let's hard code for now...and leave admin interface for next year.

**Comment by niksy** [comment]
Done.
