### ISSUE TITLE
Add field "I require accommodation"

### ISSUE THREAD

**Issue by ihabunek** [WebCampZg/conference-web#60]
In the applicant model, add a checkbox field titled: "I require accommodation" (defaults to false).
Description: "For people outside of the Zagreb area, we provide 2 nights in a hotel."

I will message the users who already submitted the talks to mark this checkbox.

**Comment by vvojvoda** [comment]
@ihabunek let's slide this to next year as cfp is over anyway.

**Comment by ihabunek** [comment]
:+1:

**Comment by denibertovic** [comment]
Fixed.
