### ISSUE TITLE
Add og tags for social networks

### ISSUE THREAD

**Issue by denibertovic** [WebCampZg/conference-web#76]
So the title, description and most importantly and image shows up when sharing on Facebook for instance. For now we can just hardcode the logo or something like that because we don't add pictures for blog posts.

**Comment by niksy** [comment]
Meta tag with `og:image` pushed on master. Dimensions of the image should be 300x300 and image should have full URL (nothing relative). We can use logo, but it’s in SVG format, and this should be JPG/PNG. @filipgjurin can you create something catchy for our Facebook users? :)
