### ISSUE TITLE
Change "Early Bird" text

### ISSUE THREAD

**Issue by dlatin** [WebCampZg/conference-web#78]
Since the Early Bird tickets have ended we should change that call to action text (above the newsletter CTA). I suggest the following changes:
"Early Bird tickets on sale!" -> "Get your WebCamp ticket now!"
"Early bird tickets are limited. Get them while they're hot." -> "Regular tickets are available, but in limited number. Get them while you can."
"If you don't want to pay for your ticket, submit a talk at one of our meetup groups!" -> ostaje isto
@ihabunek @niksy

**Comment by niksy** [comment]
Changed with https://github.com/WebCampZg/conference-web/commit/9feaf30c900341b570a279fb5f727d2a7f301090

**Comment by denibertovic** [comment]
deployed.
