### ISSUE TITLE
Mark talk as sponsored/community

### ISSUE THREAD

**Issue by ihabunek** [WebCampZg/conference-web#89]
It should be possible to mark talk as:
a) sponsored - provided  by a sponsor
b) community  - picked by the community
and reflect this in the talks page via a small label.

**Comment by denibertovic** [comment]
Added backend here: https://github.com/WebCampZg/conference-web/commit/f8147c791cd5a7ba8bb8a46b2c57e3f03843bb9e

@niksy Now it's just a matter of doing something {% if talk.is_sponsored %}LABEL{% endif %} in the templates.

**Comment by niksy** [comment]
Done.
