### ISSUE TITLE
Missing template for account profile view

### ISSUE THREAD

**Issue by vvojvoda** [WebCampZg/conference-web#9]
/accounts/profile/

**Comment by niksy** [comment]
Why do we have two different views for e-mail and password change?
Do we really need the ability to have multiple e-mail addresses?

**Comment by denibertovic** [comment]
The backend code already supports it (out of the box) so I don't see why we can't give the users the ability to update the email. As for 2 different views, they are different forms no? They can look similar, re-use the same field elements, but they are 2 different things, hence 2 views.

**Comment by denibertovic** [comment]
Btw the view mentioned in this issue is /accounts/profile, which is supposed to be the central point of a logged in user, ie, he/she can view and change info here, view submmited talks, edit them...etc.

**Comment by niksy** [comment]
@denibertovic as I can see, this view only iterates through form fields and outputs them without using partials for proper markup like on CFP. Can we get same behavior here?

**Comment by denibertovic** [comment]
Pushed to master. Let me know if this works.

**Comment by niksy** [comment]
Yup, working.
