### ISSUE TITLE
Missing web designers logo in safari

### ISSUE THREAD

**Issue by msvrtan** [WebCampZg/conference-web#92]
Cmd+r didnt help

![screen shot 2015-09-10 at 12 55 29](https://cloud.githubusercontent.com/assets/1780572/9786622/bfe304a4-57bb-11e5-8efb-18d25886d296.png)

**Comment by msvrtan** [comment]
@niksy i dalje ga nema u safariu :(

**Comment by denibertovic** [comment]
ping @niksy

**Comment by niksy** [comment]
Already up with latest deploy.

Ping @msvrtan

**Comment by denibertovic** [comment]
@msvrtan Please close if fixed.

**Comment by msvrtan** [comment]
Fixed! Tnx @niksy
