### ISSUE TITLE
Sponsor logos

### ISSUE THREAD

**Issue by msvrtan** [WebCampZg/conference-web#93]
1) Aduro idea is too high

2) Why are  locastic and styria logos much smaller then others? 

![screen shot 2015-09-10 at 12 55 29](https://cloud.githubusercontent.com/assets/1780572/9786631/dbaab52e-57bb-11e5-827f-e1e2d851c0ac.png)

**Comment by msvrtan** [comment]
@niksy ..

**Comment by ihabunek** [comment]
Vidim da je locastic png, imamo njihove vektore ovdje: https://drive.google.com/drive/u/0/folders/0B-eLdUPwAyzlcVZYM3ZwbktJbjg

**Comment by niksy** [comment]
Resolved.
